name: currensee
description: A new Flutter project
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # Core
  go_router: ^14.2.0
  provider: ^6.1.5
  shared_preferences: ^2.3.2
  lottie: ^3.1.0
  intl: ^0.18.1
  share_plus: ^7.0.0

  # UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0

  # HTTP + Local DB
  http: ^1.5.0
  sqflite: ^2.4.2
  path: ^1.9.1

  # Notifications + Config
  flutter_local_notifications: ^19.4.0
  flutter_dotenv: ^5.2.1

  # State Management
  flutter_riverpod: ^2.6.1

  # Firebase Core & Auth
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
