// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvqn9gRXPs5kC8iy7-Q_QejS65gqSihVw',
    appId: '1:418964530645:web:d85e03e383caa28ee1095c',
    messagingSenderId: '418964530645',
    projectId: 'currensee-5998b',
    authDomain: 'currensee-5998b.firebaseapp.com',
    storageBucket: 'currensee-5998b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTHnWqo8bVU66qqvlYNPtcmduxtFlJ2m0',
    appId: '1:418964530645:android:6fbabdc16db4bbe6e1095c',
    messagingSenderId: '418964530645',
    projectId: 'currensee-5998b',
    storageBucket: 'currensee-5998b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsg4nKA4Z-Sr_ZS-IximVGtw--TFvU0d8',
    appId: '1:418964530645:ios:5e4ccdd79300499be1095c',
    messagingSenderId: '418964530645',
    projectId: 'currensee-5998b',
    storageBucket: 'currensee-5998b.firebasestorage.app',
    androidClientId: '418964530645-v9585e2to1ri6jv1cncfff8anasnd9bq.apps.googleusercontent.com',
    iosClientId: '418964530645-i8k4n3u6tith8itoujvacgrf1v303nfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsg4nKA4Z-Sr_ZS-IximVGtw--TFvU0d8',
    appId: '1:418964530645:ios:5e4ccdd79300499be1095c',
    messagingSenderId: '418964530645',
    projectId: 'currensee-5998b',
    storageBucket: 'currensee-5998b.firebasestorage.app',
    androidClientId: '418964530645-v9585e2to1ri6jv1cncfff8anasnd9bq.apps.googleusercontent.com',
    iosClientId: '418964530645-i8k4n3u6tith8itoujvacgrf1v303nfn.apps.googleusercontent.com',
    iosBundleId: 'com.example.currensee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvqn9gRXPs5kC8iy7-Q_QejS65gqSihVw',
    appId: '1:418964530645:web:eade7f6a48765fd1e1095c',
    messagingSenderId: '418964530645',
    projectId: 'currensee-5998b',
    authDomain: 'currensee-5998b.firebaseapp.com',
    storageBucket: 'currensee-5998b.firebasestorage.app',
  );
}
