# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics can be disabled
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# 🔥 Use CocoaPods CDN (faster & avoids GitHub clone issues)
source 'https://cdn.cocoapods.org/'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# Use the Flutter podhelper from the SDK
require File.expand_path(File.join('/Users/moon/development/flutter', 'packages', 'flutter_tools', 'bin', 'podhelper'))

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      flutter_additional_ios_build_settings(target)
      target.build_configurations.each do |config|
        # Exclude arm64 for Intel simulators
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
